### ISSUE TITLE
all the algorithm only support two node pairs？

### ISSUE THREAD

**Issue by HuangZhanPeng** [cnclabs/proNet-core#25]
only support like
1 2
3 4

in the feature will support multiple nodes?

**Comment by chihming** [comment]
In current stage, *pronet* supports only
"nodeA" "nodeB" "weight"
format with blank (' ') separation, for instance
```
userA itemA 3
userA itemC 5
userB itemA 1
...
```
So, you hope it to support **adjacency list** or other kinds? Could you show me an example?

**Comment by HuangZhanPeng** [comment]
yes, I mean that is **adjacency list**， the format just like the deepwalk repository:
1 2 3 4 5 6 7 8 9 11 12 13 14 18 20 22 32
2 1 3 4 8 14 18 20 22 31
3 1 2 4 8 9 10 14 28 29 33
...

**Comment by chihming** [comment]
We will add this feature in the future. In edge-list format, it supports any non-negative value, including floating-point number.

In addition, if you need a program to convert your adjacency list to edge list. Please try this:
https://gist.github.com/chihming/ece2a9d36a68c6b058dc89a96be59d0f

**Comment by HuangZhanPeng** [comment]
ok，excellent，I got it，thank you very much
